/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PolylinePlot: typeof import('./components/PolylinePlot.vue')['default']
    ResultCard: typeof import('./components/ResultCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
  }
}
